### ISSUE TITLE
Package not working in vue-cli and vite default vuetify config.

### ISSUE THREAD

**Issue by RasankRam** [yikoyu/vuetify-pro-tiptap#111]
I built your project locally and tried to use in my projects. My in both vue-cli and vite projects have Vue warn as follow:

![image](https://user-images.githubusercontent.com/86410331/228921468-987081e7-3358-4ec9-bc7e-b7dc50192517.png)

By the way, due to useAttrs there is error setupContext of undefined (both vue cli and vite). But first error in my opinion critical, though I can't use your package.

**Comment by RasankRam** [comment]
import { VuetifyTiptap, VuetifyViewer,  createVuetifyProTipTap } from 'vuetify-pro-tiptap';
const VuetifyProTipTap = createVuetifyProTipTap({
  vuetify,
  lang: 'en',
  components: {
    VuetifyTiptap,
    VuetifyViewer,
  }
});

--- 

This is my how I initialized

**Comment by yikoyu** [comment]
in Vue3.x ?

[1.x](https://github.com/yikoyu/vuetify-pro-tiptap/tree/1.x) supports only Vue2.
2.x supports Vue3.x, but is under development and will be released soon

**Comment by RasankRam** [comment]
> in Vue3.x ?
> 
> [1.x](https://github.com/yikoyu/vuetify-pro-tiptap/tree/1.x) supports only Vue2. 2.x supports Vue3.x, but is under development and will be released soon

Yes, in Vue 3. I took the master branch, built the project using pnpm build:lib. Then I tried unsuccessfully to apply it to myself, it gave an error setup Context.
I created a new project using yarn create vuetify (the official command in the Getting Started section for quick build), however, I failed there too by applying your project. As I understand it, the reason is useTheme and useAttrs. I removed these things, but now it began to issue warnings, which I gave in the screenshot above.

**Comment by RasankRam** [comment]
@yikoyu 
https://github.com/RasankRam/tiptap_show_mistake

There is .git_renamed folder in folder vuetify-pro-tiptap. Renamed it to .git, if you want check your commit I started with.

**Comment by yikoyu** [comment]
> @yikoyu https://github.com/RasankRam/tiptap_show_mistake
> 
> There is .git_renamed folder in folder vuetify-pro-tiptap. Renamed it to .git, if you want check your commit I started with.

I upgraded vite，it works fine in vite V4.
![Snipaste_2023-04-01_14-06-39](https://user-images.githubusercontent.com/46991966/229269476-b12ada90-7e14-4df1-8f0e-b3ffe56727dd.png)

**Comment by RasankRam** [comment]
@yikoyu 
Thanks it works!

But don't you think that typing letters is too slow, as if with a delay?
It also works slowly on your demo version, but I thought getHTML, which is generated from the editor, was to blame for everything, but there is no such thing here

**Comment by yikoyu** [comment]
> @yikoyu Thanks it works!
> 
> But don't you think that typing letters is too slow, as if with a delay? It also works slowly on your demo version, but I thought getHTML, which is generated from the editor, was to blame for everything, but there is no such thing here

Maybe there are too many v-model in the demo version?
The VTextField for custom language is very much

**Comment by RasankRam** [comment]
@yikoyu ,
I have updated dependencies in here https://github.com/RasankRam/tiptap_show_mistake
please, You can up dev server to show slowness of the printing

**Comment by RasankRam** [comment]
Try somthing **ajsdlf;ajsdklfaspodfuasiodfjadsvjz;xclvjz** (just fast)

**Comment by RasankRam** [comment]
@yikoyu . I have checked this on two different PC. Do you have this problem?

**Comment by yikoyu** [comment]
> @yikoyu . I have checked this on two different PC. Do you have this problem?

Yes, you are right. Fast continuous input will be slow
