### ISSUE TITLE
Placeholder text is never shown

### ISSUE THREAD

**Issue by donalmurtagh** [yikoyu/vuetify-pro-tiptap#114]
If placeholder text is provided, it is never shown, even if the `value` is empty
```
<VuetifyTiptap
  value=""
  placeholder="Enter some text..."
/>
```

**Comment by dn-achim** [comment]
Hm...

I'm using 2.4.1 and placeholder is still (?) missing.
Only way to enable it seems to be the global configuration:

`  
extensions: [
    BaseKit.configure({
      placeholder: {
        placeholder: 'Enter some text...'
      }
    }),`

But I would like to prefer individual placeholders.

Any hint?

**Comment by yikoyu** [comment]
@dn-achim 
In version 2.4.2, you can override global extensions

```vue
<script setup lang="ts">
import { BaseKit, Heading } from 'vuetify-pro-tiptap'

const extensions = [
  BaseKit.configure({
    placeholder: {
      placeholder: 'Placeholder...'
    }
  }),
  Heading.configure({
    levels: [1, 2, 3, 4]
  })
]
</script>

<template>
  <VuetifyTiptap :extensions="extensions" />
</template>
```

This will only use the extension configurations on VuetifyTiptap.extensions, and the button positions remain unchanged!

**Comment by dn-achim** [comment]
That works pretty well, thank you! @yikoyu
