### ISSUE TITLE
Moving the cursor down when writing text in demo-github.io

### ISSUE THREAD

**Issue by RasankRam** [yikoyu/vuetify-pro-tiptap#132]
Hi. First of all, I want to say thank you for the wonderful package.
In general, there is a problem that when I write some text in https://yikoyu .github.io/vuetify-pro-tiptap / ,
then in the process of writing , the cursor throws down

![chrome_CgoZga2Ys6](https://github.com/yikoyu/vuetify-pro-tiptap/assets/86410331/b4f7bdc4-51d5-40ce-8b44-435892dcbb46)

I would like you to comment on this behavior

**Comment by yikoyu** [comment]
When I change the value to 20, the cursor does not drift, but long press continuous input will be a bit laggy, I will try some other methods.

https://github.com/yikoyu/vuetify-pro-tiptap/blob/4c898095d7b8350fd96eb0306779cd173d21217e/src/constants/define.ts#L3
