### ISSUE TITLE
How to use in nuxt 3?

### ISSUE THREAD

**Issue by duongxinh2003** [yikoyu/vuetify-pro-tiptap#141]
Thank you for creating this library. Not only me but everyone also wants to see an example/usage of how to use this module in Nuxt 3.

**Comment by yikoyu** [comment]
https://github.com/yikoyu/nuxt3-test

**Comment by yikoyu** [comment]
This is the Nuxt 3 example on CodeSandbox
[Nuxt3 CodeSandbox](https://codesandbox.io/p/sandbox/vuetify-pro-tiptap-nuxt3-ttlk6x)
