### ISSUE TITLE
[Bug report] PreviewActionButton not working

### ISSUE THREAD

**Issue by duongxinh2003** [yikoyu/vuetify-pro-tiptap#167]
Thank you for creating this library. I used this lib for my project but the feature preview not working.
When I checked the demo in Codesanbox and click button '全屏', not happen change and inspect error occurred:  `ReferenceError: editor is not defined.`

**Comment by duongxinh2003** [comment]
I resolved this. In 'PreviewActionButton.vue' file. change this code:
> `const content = computed(() => {
  return editor.getHTML();
});` 

to
`const content = computed(() => {
  return props.editor?.getHTML();
});`

**Comment by yikoyu** [comment]
The issue is not repeated in [codesanbox](https://codesandbox.io/p/sandbox/vuetify-pro-tiptap-codesandbox-4pvcqm?file=/src/components/PreviewActionButton.vue).
