### ISSUE TITLE
Option to remove default HTML wrapper

### ISSUE THREAD

**Issue by p1xel007** [yikoyu/vuetify-pro-tiptap#208]
Currently by default the content is wrapped with **&lt;p&gt;&lt;/p&gt;** tags

Is it possible to remove this default &lt;p&gt;&lt;/p&gt; tags from the content and have just the raw content without any html tags wrapped around them, and only add tags by selecting from the menu?

**Comment by yikoyu** [comment]
https://github.com/ueberdosis/tiptap/issues/154

I think it can be like this.

https://github.com/yikoyu/vuetify-pro-tiptap/blob/808d9ce684e9f05650f521ead1df3491118723a3/src/components/VuetifyTiptap.vue#L149..L154

```typescript
function getOutput(editor: CoreEditor, output: Props['output']) {
  if (output === 'html') return editor.isEmpty ? '' : editor.getHTML()
  if (output === 'json') return editor.isEmpty ? {} : editor.getJSON()
  if (output === 'text') return editor.isEmpty ? '' : editor.getText()
  return ''
}
```

If everything goes smoothly, it will be fixed in v2.3.1.
