### ISSUE TITLE
How do I add commands from a tiptap extension?

### ISSUE THREAD

**Issue by ianrafael2001** [yikoyu/vuetify-pro-tiptap#234]
want to add tiptap extensions ([tiptap ](https://tiptap.dev/extensions)) but I can't.
How do I add them?

Edit: i'm trying in @1.4.3

**Comment by yikoyu** [comment]
In version 1.x, you can try using the extensions prop of VuetifyTiptap.
Additionally, the 1.x version of Vue2 is no longer being updated.

[1.x README](https://github.com/yikoyu/vuetify-pro-tiptap/tree/1.x?tab=readme-ov-file#props-1)
