### ISSUE TITLE
Adding images from file failes

### ISSUE THREAD

**Issue by GrantAnt** [yikoyu/vuetify-pro-tiptap#237]
Hi,

I have just installed the latest version (2.3.0) with extension-image: 2.1.10. I can add images by URL, but I can't add images from filesystem since the button "Apply" is locked when I have "Upload" open. 

"Apply" only unlocks when under "URL" a link is inserted. In this case the image from the link is shown.

Thanks!

**Comment by leo1200** [comment]
If you specify the upload function not globally but within components, it can be done as follows:
```
    const extensions = [
      BaseKit.configure({
        placeholder: {
          placeholder: 'Enter some text...'
        }
      }),
      Bold,
      Italic,
      Underline,
      Strike,
      Color,
      Highlight,
      Heading,
      Image.configure({
        upload(file: File) {
          // you upload function returning Promise<string>
          return uploadImage(file)
        }
      }),
      Link,
      Table,
      History
    ]
```

**Comment by phyothiha** [comment]
I'm still have a problem uploading image from file system. Image upload function didn't run in my component and also there is no console error. I choose a file and fill out link value to unlock Apply button.
