### ISSUE TITLE
Interference with other styles

### ISSUE THREAD

**Issue by RogierVC** [yikoyu/vuetify-pro-tiptap#276]
After installing and using this package, existing input styles gets overridden.
Styles of this package should be isolated or uniquely named so it won't interfere with other styles.

![image](https://github.com/yikoyu/vuetify-pro-tiptap/assets/34268966/949dad06-8d48-45f1-b0b0-eaf521c0df38)

**Comment by yikoyu** [comment]
This is the compiled CSS [link](https://cdn.jsdelivr.net/npm/vuetify-pro-tiptap@2.4.3/lib/style.css). You can format it to check it, and the styles are all in `.vuetify-pro-tiptap`. There should be no problem of CSS being overwritten.
