### ISSUE TITLE
Configure paste and drop files

### ISSUE THREAD

**Issue by inferno332** [yikoyu/vuetify-pro-tiptap#292]
How can I configure my own file upload using Paste or Drop, like the original tiptap FileHandler
![image](https://github.com/yikoyu/vuetify-pro-tiptap/assets/49389380/c8408aa2-74d9-4718-a14d-a7d6e9fdaa0d)

**Comment by yikoyu** [comment]
FileHandler is not supported, and you need to be able to encapsulate the extension by yourself
