### ISSUE TITLE
feature: Link extras

### ISSUE THREAD

**Issue by SergkeiM** [yikoyu/vuetify-pro-tiptap#309]
Hi @yikoyu 

Thank you for this package saved me a lot of time.

I think Link is missing some functionily:

1. Unlink
2. Target attribute
3. Rel attribute

Based on this: https://github.com/yikoyu/vuetify-pro-tiptap/blob/154be3b24f7b4a7217f14b7938eb0d8dba0bf762/src/extensions/components/LinkActionButton.vue#L33

I see only `href` is used, is ok to create a PR to add more to link?

Note: I didn't figured out how to add `Unlink` functionility 

From what I see this pacakge was heavily inspired by https://github.com/Leecason/element-tiptap

In `element-tiptap` they have used a different aproach to bubble menu, are you planning anything like that?

**Comment by yikoyu** [comment]
@SergkeiM  Regarding the demand for link expansion, you can check out this PR. https://github.com/yikoyu/vuetify-pro-tiptap/pull/312

**Comment by SergkeiM** [comment]
Hi @yikoyu 

Whooha looks good, didn't expect it so fast, I was actuallly planning to contribute :)
