### ISSUE TITLE
release 2.5.1 Node >18 incompatibility

### ISSUE THREAD

**Issue by IliassB** [yikoyu/vuetify-pro-tiptap#337]
I was on the 2.4.3 release and could use the package with no problems, when I upgraded to the latest release (2.5.1), I get the following error during installation.

```bash
error vuetify-pro-tiptap@2.5.1: The engine "node" is incompatible with this module. Expected version "^18.0.0". Got "20.11.1"
warning vuetify-pro-tiptap@2.5.1: The engine "pnpm" appears to be invalid.
error Found incompatible module.
```

I saw that the engine in package.json was changed:

Release 2.4.3
```json
  "engines": {
    "node": ">=16",
    "pnpm": ">=7"
  },
```

Release 2.5.1
```json
  "engines": {
    "node": "^18.0.0",
    "pnpm": "^8.0.0"
  },
```

Is there a particular reason for this change ?

**Comment by yikoyu** [comment]
I guess you might be using yarn, pnpm and npm does not enable engine-strict by default.
This sentence is for renovate to now update dependencies to the latest version with pnpm and node.
The pnpm-lock.yaml will be forcibly upgraded to 9.0.
Before upgrading to pnpm V9, you can temporarily use:
```
yarn add vuetify-pro-tiptap --ignore-engines
```
Or if you have other locked versions of pnpm and node that renovate uses, you can tell me.

**Comment by IliassB** [comment]
Indeed I do use yarn, in my case, using the ignore-engines option worked, when is it planned to upgrade to pnpm V9 ?

I can add the option in a .yarnrc to apply it by default for my project, but would rather keep this check in my dev environement.
