### ISSUE TITLE
cant extend Image extension

### ISSUE THREAD

**Issue by VIXI0** [yikoyu/vuetify-pro-tiptap#338]
CANT REMOVE Image extension
i want to add a token to image before it load but it doesnt matter what changes  i do to the extension it doest reflect on tiptap, the weird thing is that it doesnt matter if i remove the extension it still show the option.

![image](https://github.com/yikoyu/vuetify-pro-tiptap/assets/43118641/5ed44b26-0f1d-4a1d-8095-0c255c85a670)

const extensions = [
  BaseKit.configure({
    placeholder: {
      placeholder: 'Escribe aquí...'
    }
  }),
  Bold,
  Italic,
  Underline,
  Strike,
  Color,
  Highlight,
  Heading,
  Link,
  // Image.configure({
  //     // Generate a VDivider after the button
  //     divider: true,
  //     token: TokenImage.value?TokenImage.value:'',
  //     // Custom image tabs
  //     // imageTabs: [{ name: 'SELECT', component: markRaw(SelectImage) }],
  //     // hidden default tab
  //     // hiddenTabs: ['upload'],
  //     // custom upload function
  //     async upload(file) {
        
  //     const formData = new FormData()
  //     formData.append('file', file[0])

  //     try {
  //       const { data } = await useAPI('/images', {
  //         method: 'POST',
  //         body: formData
  //       })

  //       const imageUrl = `http://localhost:3000/images/${data.value.file}` // Ajusta según la respuesta de tu API
  //       return Promise.resolve(imageUrl)
  //     } catch (error) {
  //       console.error('Error uploading image:', error)
  //       return Promise.reject(error)
  //     }
  //   }
  //   }),
  Video,
  Table,
  Fullscreen,
  History
]

**Comment by yikoyu** [comment]
I am unable to reproduce the issue here. Please provide a repository or a CodeSandbox link that can reproduce the problem.

**Comment by VIXI0** [comment]
sadly I tryed to create a empty repo only with vuetify-pro-titap but i get this error  

✘ [ERROR] Could not resolve "vuetify/components"
 ../node_modules/vuetify-pro-tiptap/lib/vuetify-pro-tiptap.mjs:4:447

✘ [ERROR] Could not resolve "vuetify"
../node_modules/vuetify-pro-tiptap/lib/vuetify-pro-tiptap.mjs:6:31

Steps to reproduce:

1. yarn create vuetify
2. yarn add vuetify-pro-titap
3. create tiptap.ts like the docs says
4. import and use it in app.vue

**Comment by yikoyu** [comment]
I am using the latest version of vuetify-pro-tiptap and did not find this issue. Please provide the repository to reproduce the problem.
