### ISSUE TITLE
本地图片上传成功但是无法触发事件 这是为什么呀

### ISSUE THREAD

**Issue by hongdundada** [yikoyu/vuetify-pro-tiptap#370]
![image](https://github.com/user-attachments/assets/3ccbae4a-0898-4de6-b43d-e529da118fbc)

![image](https://github.com/user-attachments/assets/c432feed-9a9d-4438-90ca-c591e21f56d4)

本地图片上传成功但是无法触发事件 这是为什么呀
拜托大佬了 不知道为什么连事件都无法进行触发 

![Uploading image.png…]()

**Comment by yikoyu** [comment]
请提供仓库或者codesanbox链接

**Comment by hongdundada** [comment]
> 请提供仓库或者codesanbox链接
https://gitee.com/maozhean/rich-text.git
git clone https://gitee.com/maozhean/rich-text.git

上面如果不行可以直接用下面连接下载-直接就可以从网页上下载了
十分感谢大佬。

通过百度网盘分享的文件：code-tiptap.rar
链接：https://pan.baidu.com/s/1P8oMK_zMTCvnKITYCkAcCA 
提取码：1234 
--来自百度网盘超级会员V8的分享

代码在这个路由文件
![image](https://github.com/user-attachments/assets/fe8254b4-0d13-46fa-bad6-5baaf23b4e8c)

**Comment by hongdundada** [comment]
> 请提供仓库或者codesanbox链接

大佬我试了一下如果不穿extensions 是一个ko空数组 那么上传图片是没有问题的

![image](https://github.com/user-attachments/assets/0a05fb89-7fae-4c10-b606-3886eb41c436)


![image](https://github.com/user-attachments/assets/794d755b-110c-4983-8853-3453432d2e70)

还有一个问题不知道为什么这个复选框 opacity初始化是0 我只能人为手动调整为1

**Comment by yikoyu** [comment]
全局定义extensions会被局部定义的覆盖，如果对弹框不满意，可以使用 `dialogComponent` ，examples里面有例子。

**Comment by hongdundada** [comment]
> 全局定义extensions会被局部定义的覆盖，如果对弹框不满意，可以使用 `dialogComponent` ，examples里面有例子。

![image](https://github.com/user-attachments/assets/77a7544d-1219-4091-8185-c4bfe7d5c67d)
还有一个问题大佬你本地图片 回显可以显示吗。

**Comment by yikoyu** [comment]
> > 全局定义extensions会被局部定义的覆盖，如果对弹框不满意，可以使用 `dialogComponent` ，examples里面有例子。
> 
> ![image](https://private-user-images.githubusercontent.com/61041443/369308003-77a7544d-1219-4091-8185-c4bfe7d5c67d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTgxOTQsIm5iZiI6MTcyNjgxNzg5NCwicGF0aCI6Ii82MTA0MTQ0My8zNjkzMDgwMDMtNzdhNzU0NGQtMTIxOS00MDkxLTgxODUtYzRiZmU3ZDVjNjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA3MzgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyOGQwOTQ0ZjRkYzZkNDcyOTg4YTFmNGQxOTRjM2NiMGQ5NDEwMjZkNzZmZjkxMmYzNjM2NzBkZGI4NTg4ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hcrw_h25Emj6Joa6twqYiYbJ_tX-yzTLbeX-LciVcpQ) 还有一个问题大佬你本地图片 回显可以显示吗。

`URL.createObjectURL(file)`只是创建了一个blob url，是可以回显的，你需要把它换成你的上传接口

**Comment by hongdundada** [comment]
> > > 全局定义extensions会被局部定义的覆盖，如果对弹框不满意，可以使用 `dialogComponent` ，examples里面有例子。
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/61041443/369308003-77a7544d-1219-4091-8185-c4bfe7d5c67d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTgxOTQsIm5iZiI6MTcyNjgxNzg5NCwicGF0aCI6Ii82MTA0MTQ0My8zNjkzMDgwMDMtNzdhNzU0NGQtMTIxOS00MDkxLTgxODUtYzRiZmU3ZDVjNjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA3MzgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyOGQwOTQ0ZjRkYzZkNDcyOTg4YTFmNGQxOTRjM2NiMGQ5NDEwMjZkNzZmZjkxMmYzNjM2NzBkZGI4NTg4ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hcrw_h25Emj6Joa6twqYiYbJ_tX-yzTLbeX-LciVcpQ) 还有一个问题大佬你本地图片 回显可以显示吗。
> 
> `URL.createObjectURL(file)`只是创建了一个blob url，是可以回显的，你需要把它换成你的上传接口

![image](https://github.com/user-attachments/assets/ddbe3391-200d-4b4a-ad0a-c5f7a0ef294e)


回显需要对数据进行特殊处理吗。 因为拿本地存储数据的时候就会直接报错    换成我的上传接口(需要我把图片存储到服务器吗。本地有办法实现吗。)

**Comment by yikoyu** [comment]
> > > > 全局定义extensions会被局部定义的覆盖，如果对弹框不满意，可以使用 `dialogComponent` ，examples里面有例子。
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/61041443/369308003-77a7544d-1219-4091-8185-c4bfe7d5c67d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTgxOTQsIm5iZiI6MTcyNjgxNzg5NCwicGF0aCI6Ii82MTA0MTQ0My8zNjkzMDgwMDMtNzdhNzU0NGQtMTIxOS00MDkxLTgxODUtYzRiZmU3ZDVjNjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA3MzgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyOGQwOTQ0ZjRkYzZkNDcyOTg4YTFmNGQxOTRjM2NiMGQ5NDEwMjZkNzZmZjkxMmYzNjM2NzBkZGI4NTg4ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hcrw_h25Emj6Joa6twqYiYbJ_tX-yzTLbeX-LciVcpQ) 还有一个问题大佬你本地图片 回显可以显示吗。
> > 
> > 
> > `URL.createObjectURL(file)`只是创建了一个blob url，是可以回显的，你需要把它换成你的上传接口
> 
> ![image](https://private-user-images.githubusercontent.com/61041443/369326856-ddbe3391-200d-4b4a-ad0a-c5f7a0ef294e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MzUxMDMsIm5iZiI6MTcyNjgzNDgwMywicGF0aCI6Ii82MTA0MTQ0My8zNjkzMjY4NTYtZGRiZTMzOTEtMjAwZC00YjRhLWFkMGEtYzVmN2EwZWYyOTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEyMjAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzODAwNTRjOGMzZDYwNDI4NzA3NmNlNGY1YzJiMDBhNGM3NWZlOGJhZjc0OTEwMTg3MzViZmM0MTFlMmJmMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Yq5M4PFA7S0MBAswfAPHjcwwafyO4CdHa0sKMhgAytY)
> 
> 回显需要对数据进行特殊处理吗。 因为拿本地存储数据的时候就会直接报错 换成我的上传接口(需要我把图片存储到服务器吗。本地有办法实现吗。)

我 edge 和 chrome 正常，你是什么浏览器？
只要提供一个链接就行了，当然图片小的话，你也能使用base64。
blob url 只是一个演示方案，浏览器刷新会被释放的。

**Comment by hongdundada** [comment]
> > > > > 全局定义extensions会被局部定义的覆盖，如果对弹框不满意，可以使用 `dialogComponent` ，examples里面有例子。
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/61041443/369308003-77a7544d-1219-4091-8185-c4bfe7d5c67d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTgxOTQsIm5iZiI6MTcyNjgxNzg5NCwicGF0aCI6Ii82MTA0MTQ0My8zNjkzMDgwMDMtNzdhNzU0NGQtMTIxOS00MDkxLTgxODUtYzRiZmU3ZDVjNjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA3MzgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyOGQwOTQ0ZjRkYzZkNDcyOTg4YTFmNGQxOTRjM2NiMGQ5NDEwMjZkNzZmZjkxMmYzNjM2NzBkZGI4NTg4ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hcrw_h25Emj6Joa6twqYiYbJ_tX-yzTLbeX-LciVcpQ) 还有一个问题大佬你本地图片 回显可以显示吗。
> > > 
> > > 
> > > `URL.createObjectURL(file)`只是创建了一个blob url，是可以回显的，你需要把它换成你的上传接口
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/61041443/369326856-ddbe3391-200d-4b4a-ad0a-c5f7a0ef294e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MzUxMDMsIm5iZiI6MTcyNjgzNDgwMywicGF0aCI6Ii82MTA0MTQ0My8zNjkzMjY4NTYtZGRiZTMzOTEtMjAwZC00YjRhLWFkMGEtYzVmN2EwZWYyOTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEyMjAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzODAwNTRjOGMzZDYwNDI4NzA3NmNlNGY1YzJiMDBhNGM3NWZlOGJhZjc0OTEwMTg3MzViZmM0MTFlMmJmMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Yq5M4PFA7S0MBAswfAPHjcwwafyO4CdHa0sKMhgAytY)
> > 回显需要对数据进行特殊处理吗。 因为拿本地存储数据的时候就会直接报错 换成我的上传接口(需要我把图片存储到服务器吗。本地有办法实现吗。)
> 
> 我 edge 和 chrome 正常，你是什么浏览器？ 只要提供一个链接就行了，当然图片小的话，你也能使用base64。 blob url 只是一个演示方案，浏览器刷新后blob url会被释放的。

明白了大佬 那我用base64存储吧。我用的是chorme浏览器 可以正常显示出来 只不过 从缓存localStorage里面取出数据 进行回显(页面刷新就不可以了。)
谢谢大佬。
