### ISSUE TITLE
为什么文本高亮和文本颜色 都没有CSS样式-是缺少什么引入吗

### ISSUE THREAD

**Issue by hongdundada** [yikoyu/vuetify-pro-tiptap#371]
![image](https://github.com/user-attachments/assets/7eecbb2e-cb35-4f5e-87e5-0ac94f091261)
![image](https://github.com/user-attachments/assets/bc255deb-dc97-4948-9a6c-fffb5e2435fc)

为什么文本高亮和文本颜色 都没有CSS样式-是缺少什么引入吗

**Comment by yikoyu** [comment]
请提供仓库或者codesanbox链接

**Comment by hongdundada** [comment]
> 请提供仓库或者stackblitz链接 这是demo [Stackblitz](https://stackblitz.com/~/github.com/yikoyu/vuetify-pro-tiptap-demo/tree/main) 可以看这个demo排查一下

我找到原因了 是因为和其他CSS冲突了
