### ISSUE TITLE
Adjust heading styles and sizes

### ISSUE THREAD

**Issue by Montags24** [yikoyu/vuetify-pro-tiptap#400]
Hi, sorry if this is highlighted in the docs already, but is there a way to change the default styling for headings? I’d like to be able to change the font size, colour and styles for the available H1-6 and p tags in the heading extension. Thank you. Great work btw really love this project!

**Comment by yikoyu** [comment]
https://github.com/yikoyu/vuetify-pro-tiptap/issues/307#issuecomment-2076715995

**Comment by Montags24** [comment]
Fsntastic!
