### ISSUE TITLE
File selection event does not work for ImageUpload

### ISSUE THREAD

**Issue by gezilein** [yikoyu/vuetify-pro-tiptap#405]
`v-file-input` _@change_ event is no longer working since the event is not trusted (see this [playground](https://play.vuetifyjs.com/#eNpdT01rwzAM/SuaGaSFNbmXtGyXsfsGOyyDGlfpDI5sbDkwTP57HaeUthdjPT29j58kglfNm3P1GFFsRcs4OCMZ9x0BtONGOle+ZVCWWGpCf4EK2GuDG00uMryqP0kn3HXC0nuGP9GgYjx2Yt82t8zrfUowhBNM08Ujs+5NZmTJ0DY32fIYlNeOISDHJaIenPUMCTz2MEHv7QBVrlXNdICsG7i47WbGqvpAYyx8W2+OT9V6IcnwTwr6SIq1JbivscIRideQlrBZqh6liZgFD2VV6/DlY8jULTynB2g6zGe5aNss0XNoMb1QNKY8v2dXJ4fr)).

**Comment by yikoyu** [comment]
Hello, in my case, event.isTrusted is working properly.

![image](https://github.com/user-attachments/assets/2707be70-ca62-4746-a0d5-9a30ea93b2af)

You can see that @change is a native event in the input tag.
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VFileInput/VFileInput.tsx#L248

**Comment by gezilein** [comment]
> Hi, in my case, event.isTrusted is working properly.
> 
> ![image](https://private-user-images.githubusercontent.com/46991966/393147880-2707be70-ca62-4746-a0d5-9a30ea93b2af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MDk2MjcsIm5iZiI6MTczMzUwOTMyNywicGF0aCI6Ii80Njk5MTk2Ni8zOTMxNDc4ODAtMjcwN2JlNzAtY2E2Mi00NzQ2LWEwZDUtOWEzMGVhOTNiMmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDE4MjIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZjIwNzMyNjQ1OWU4ZWE1NDFhNmM1MDkzMDYwZmNkNGFkNjk0ODQwYjU5MmFkMmJlZGIyNzI5YjkwZWVlZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gtaBv-eXn4h9f1xCdqCqxdROxdNGZ-b3BEqrqAX6BMs)
> 
> You can see that @change is a native event in the input tag. https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VFileInput/VFileInput.tsx#L248

Yes, indeed. That's what was driving me crazy. And even in playground I think once it was trusted but on subsequent selections not anymore.
It also shouldn't be browser specific. Unless it's some browser extension to blame? 🤔

In any case I ended up adjusting the code for my own custom component so PR is maybe not necessary.
If other people aren't reporting problems it might really just be my machine's fault...
